[package]
name = "ghost_git_writer"
description = "ggw provide that git commit msg and diff summary etc by LLM"
version = "0.9.1"
repository = "https://github.com/Uliboooo/ghost_git_writer"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Uliboooo uliboulibo@gmail.com"]

[[bin]]
name = "ggw"
path = "src/main.rs"

[profile.release]
opt-level = "z"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
git2 = "0.20.2"
ollama-rs = "0.3.2"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread"] }
llm-api-rs = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
derive-getters = "0.5.0"
chrono = "0.4.41"
dialoguer = "0.11.0"
home = "0.5.11"
easy_storage = "0.3.2"
