[package]
name = "ghost_git_writer"
description = "write a git commit message, README or Diff Summary by LLM services."
version = "0.15.1"
repository = "https://github.com/Uliboooo/ghost_git_writer"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Uliboooo uliboulibo@gmail.com"]

[[bin]]
name = "ggw"
path = "src/main.rs"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
clap = { version = "4.5.*", features = ["derive"] }
git2 = "0.20.*"
ollama-rs = "0.3.*"
tokio = { version = "1.47.*", features = ["rt", "rt-multi-thread"] }
llm-api-rs = "0.1.*"
serde = { version = "1.0.*", features = ["derive"] }
derive-getters = "0.5.*"
chrono = "0.4.*"
home = "0.5.*"
easy_storage = "0.3.*"
indicatif = "0.18.*"
unicode-width = "0.2.1"
url = "2.5.7"
